# Generated by Django 5.2.4 on 2026-09-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_alter_store_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('add_products', 'Can add products'), ('change_products', 'Can change products'), ('delete_products', 'Can delete products'), ('view_products', 'Can view products'), ('buy_products', 'Can buy products')]},
        ),
    ]
